version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Enable Label, means containers to be watch have to declare label
      # "com.centurylinklabs.watchtower.enable=true"
      WATCHTOWER_LABEL_ENABLE: true

      WATCHTOWER_SCHEDULE: "{{ watchtower.schedule }}"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_TIMEOUT: 30s
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_NOTIFICATIONS_LEVEL: info
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "{{ watchtower.hostname }}"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "{{ watchtower.email_from }}"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "{{ watchtower.email_to }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "{{ watchtower.email_server }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "{{ watchtower.email_server_port }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "{{ watchtower.email_server_user }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "{{ watchtower.email_server_password }}"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
