- name: Prepare destination server for move
  hosts: target
  gather_facts: no
  become: yes
  tasks:
    - name: Create a SSH key for user
      ansible.builtin.user:
        name: "{{ansible_user}}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    - name: Download public part of the SSH key
      ansible.builtin.fetch:
        src: ".ssh/id_rsa.pub"
        dest: ./tmp/
        flat: true
