- name: Backup System
  hosts: target
  become: yes
  roles:
    - backup-folder-prepared
    - traefik-backup
    - mailcow-backup
    - joplin-backup
    - wireguard-backup
    - vaultwarden-backup
    - nextcloud-backup
    - backup-bundle-created
