services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      ADMIN_TOKEN: "{{ vaultwarden.admintoken }}"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_web
      - traefik.http.routers.vaultwarden.rule=Host(`{{ vaultwarden.url }}`)
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
