api:
  # Enable the dashboard
  dashboard: true
  # Enable the API in insecure mode
  insecure: true

global:
  # Do not send anonymous usage data
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"
    http:
      tls:
        certResolver: my-dns-chlng

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik_web"
  file:
    filename: /etc/traefik/dynamic-config.yml
    watch: true

certificatesResolvers:
  my-dns-chlng:
    acme:
      email: "{{ traefik.letsencrypt_mail }}"
      storage: /var/traefik/acme.json
      dnsChallenge:
        provider: "{{ traefik.dns_challenge.provider }}"
        delayBeforeCheck: "600"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
