- name: Folder for wireguard should exist
  file:
    path: "{{ wireguard.installpath }}"
    state: directory
    mode: "0644"
- name: Copy docker files to server
  template:
    src: ../files/{{ item }}
    dest: "{{ wireguard.installpath }}{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml

- name: Stop wireguard
  shell:
    cmd: "docker compose down"
    chdir: "{{ wireguard.installpath }}"
- name: Run wireguard
  shell:
    cmd: "docker compose up -d"
    chdir: "{{ wireguard.installpath }}"
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
